import numpy as np
import math


#RESOLUTION
RESOLUTION = 256
DISPLAY_RESOLUTION = 256

# CONV KERNALE FROM 64 OR 32
KERNEL_NUM = 64

USE_AVG_POOLING = False
USE_MAX_POOLING = True

CHANGE_INPUT = True# concat input to pooling
COMBINE_POOLING_INPUT = False

LINUX_EXP=True

BASE_PATH = './'

ONLY_DEPTH = True